theme: jekyll-theme-minimal
title: Whitey's TF2 Key Bot
description: Team Fortress 2 KEY 絕地要塞2 金鑰交易機器人，下單並完成繳費後即可取貨無需等待。目前提供四大超商代碼繳費，方便沒有信用卡的玩家購買。
logo: https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/83/83858abbec5112e8312a787df7d5f47da6f17e62_full.jpg
google_analytics: G-KXXVTV8V14
default_stock: 300
